variables:
  GO_IMAGE: golang:latest

stages:
  - test
  - build

####################################################################################################
## Test
####################################################################################################

test:
  image: $GO_IMAGE
  stage: test
  script:
    - make test

####################################################################################################
## Build
####################################################################################################

build:
  image: $GO_IMAGE
  stage: build
  script:
    - make build
